all:
	mipsel-linux-gcc main.c -o overclock.dge -lSDL_image -lSDL_ttf -I`sdl-config --cflags --libs` 
	#gcc main.c -g -o overclock -DDEBUG -lSDL_image -lSDL -lSDL_ttf -I/usr/include/SDL
clean:
	rm -rf overclock.dge
