
INCLUDEPATH := /home/jack/buildroot-2017.02.9/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include
INCLUDES := -I$(INCLUDEPATH) -I$(INCLUDEPATH)/SDL

ARCH	:= mipsel-linux-
CC		:= $(ARCH)g++
CXX = $(ARCH)g++
CXXFLAGS  := -O2 -Wall $(INCLUDES)
LDFLAGS := -O2 -Wall -s -lpng -lSDLmain -lSDL -lSDL_gfx -lSDL_image
SOURCES := *.o

PROGRAM = main
TARGET	:= viewimage.dge
VERSION	=	1.0

all: $(PROGRAM)
	mv $(PROGRAM) $(TARGET)

clean:
	rm -f $(TARGET) *.o *~
